language: node_js
node_js:
  - "lts/*"
script: npm run test-coverage
env:
  # Don't think about reusing this somewhere else, it's for testing.
  - IRON_SECRET="r2(@DwwVWciKUqKk?ceiXEU9rGGLjFdMJbEnywNr"
after_success: npx codecov
